name: booky_camera_app
description: Android app to take picture of books, group them by bundle, add the weight and state metadata

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-305.0.dev <4.0.0'

dependencies:
  camera: ^0.10.3+2
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true